"""empty message

Revision ID: 88e12c155696
Revises: 9c6b363c66ed
Create Date: 2018-02-06 14:29:52.038144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e12c155696'
down_revision = '9c6b363c66ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulcrum_survey_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_status_code_association',
    sa.Column('fulcrum_survey_id', sa.Integer(), nullable=True),
    sa.Column('fulcrum_survey_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fulcrum_survey_id'], ['fulcrum_survey.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fulcrum_survey_status_id'], ['fulcrum_survey_status.id'], onupdate='CASCADE', ondelete='SET NULL')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_status_code_association')
    op.drop_table('fulcrum_survey_status')
    # ### end Alembic commands ###
