"""empty message

Revision ID: 9c6b363c66ed
Revises: 
Create Date: 2018-02-06 13:03:22.927144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6b363c66ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulcrum_survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('reconciliation_status_code', sa.Text(), nullable=True),
    sa.Column('survey_status_code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fulcrum_survey')
    # ### end Alembic commands ###
